### ISSUE TITLE
Blinddocking - After Final Docking with selected binding site, 'Next' button takes you back to 'Blind Docking Output' tab

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#10]
Hi,

Once I select binding site predicted by sw and go for docking, After clicking 'next' (upon job completion), it takes you back into 'Blind Docking Output'. Instead it should take you forward to Docking Details - display docking score and binding energy plots and other plots.

**Comment by mdaakhan** [comment]
Fixed with Commit id 986de25
