### ISSUE TITLE
Number of conformation in decimals in graphs

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#100]
PRinS_V_2_0_0

In docking data analysis, the graph displays numbers of conformations in decimal when it should be whole numbers.
![image](https://user-images.githubusercontent.com/111036161/195023655-85726d3f-12a8-40e3-99ac-48ecf89880bb.png)

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
