### ISSUE TITLE
'Set' to select MD combinations is not working properly

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#101]
PIPL01
PRinS_V_2_0_0 - windows version

When I set the cut off at -9 for selection, there should be 10 complexes that should go forward out of 14. here it took only 6. 
![image](https://user-images.githubusercontent.com/111036161/195025295-8a89ad2f-18c2-4928-bffe-838eb751ff00.png)
![image](https://user-images.githubusercontent.com/111036161/195025368-d63e684e-3663-495f-96d7-8f92ef3f63dd.png)

**Comment by chandkc** [comment]
@ADHITHYA46 Pl. check.

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
