### ISSUE TITLE
Docking Job details

### ISSUE THREAD

**Issue by gurdev7** [chandkc/X-ESS#103]
After setting docking grid parameters, I always click on the next button instead of setting docking job details. It is still confusing. Either disable the next button or forward me to the docking job details page.

<img width="1338" alt="Screenshot 2022-10-18 at 10 50 14 AM" src="https://user-images.githubusercontent.com/113581903/196342309-8b698efb-e0dc-40fb-a3aa-286292382136.png">

**Comment by mdaakhan** [comment]
Fixed and will be available in next release
