### ISSUE TITLE
MD to FES: Values in Table not getting populated

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#106]
Hi,

PRinS_V_2_0_2_Windows and PRinS_V_2_0_2_Test
Windows machine (PIPL01) and Insilico (Linux)

At both machines, I tried MD and then while going for FES, we come at tab "Select Combinations for Free Energy" where we have to select combinations based on Combined rank and scores such as RMSD Rank, Internal Energy Rank and etc. So all these scores and ranks are showing zeros (0). Earlier they used to show 0.33 or 0.64 something like this. 

Both this were tried on different machines with respective exes with different examples. No bias. 

Linux system
![FES_Insilico](https://user-images.githubusercontent.com/105902516/196693410-ec1984f9-36ed-4b98-aafc-13e1b180e66f.png)

Windows system
![FES_PIPL01](https://user-images.githubusercontent.com/105902516/196693506-b2c97fe4-c66f-4467-ba81-63e32658bb20.png)

**Comment by chandkc** [comment]
@SumedhaBhosale Try with atleast 4-5 combinations

**Comment by mdaakhan** [comment]
Bug Fixed, V2.1
