### ISSUE TITLE
Cancel button for ligand topology generation 

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#109]
**PRinS_Ubuntu_20_86X64_2_0_0**
In MD Simulation during ligand topology generation, if I click on _Cancel_ button it still opens the SwissParam website

[X_ESS_swissparam.webm](https://user-images.githubusercontent.com/117424735/203490737-ef4d7140-8c28-47a2-95ce-652e0dd711e0.webm)

**Comment by mdaakhan** [comment]
Fixed in V2.3
