### ISSUE TITLE
MD2FES Table-01

### ISSUE THREAD

**Issue by chandkc** [chandkc/X-ESS#11]
1. Rename the table as HBond Rank
2. Place "MMPBSA Energy" as a weighting factor
3. If difference in CoM distance of (docking - MD) > 1.5 nm ==> Flag with Red Color

![IMG-4722](https://user-images.githubusercontent.com/105489779/185102156-fc887ed4-e1dd-4339-bd71-25c0c615fc5c.jpg)

**Comment by mdaakhan** [comment]
Commit GIT ID - 75ac911b69a9abe95b62a379c3a96f517776ef32 (V1)
Commit GIT ID b8b3cc8519f52f4636c4e8d8aab0abf7e08bedb1 (V2)

Ranking for Interaction Energy and RMSD is supposed to be 0 for their highest value, and 1 for the lowest value (preferred). Corrected this. H-bond ranking was in order.

**Comment by chandkc** [comment]
1 and 3 Completed
2 is remaining.

**Comment by chandkc** [comment]
All implemented in v2
