### ISSUE TITLE
Docked Pose - Ligand Interaction view

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#110]
**PRinS_Ubuntu_20_86X64_2_0_0**

- I selected few poses in Docked Pose. The same poses are getting selected for Ligand Interaction view and Target-Ligand Interaction Profile.
- Now the poses are already selected but it is not showing anything unless I select/unselect something.
- Even after unselecting everything one pose stays in the visualizer.

[XESS_visualiser.webm](https://user-images.githubusercontent.com/117424735/203529995-55f41e7a-f33b-48be-b6a6-ff2a78e13cdc.webm)

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
