### ISSUE TITLE
One ligand is absent in results

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#112]
**PRinS_Ubuntu_20_86X64_2_0_0**

Performed blind docking for protein (pdb id 3ERT) with 5 compounds. In the docking job details it shows that 5 docking is completed but the results only include 4 compounds. The IO_DIR includes 23 files but the project directory only had 6 files for that particular job id.

Suggestion - The x-axis should only include those names/ids who are selected for docking 

![XESS_4](https://user-images.githubusercontent.com/117424735/203770031-08d14ed4-c91b-4364-9e4d-1fa18cca9b0b.png)
![XESS_3](https://user-images.githubusercontent.com/117424735/203770046-b7fb8dc4-5020-4912-a30f-c28ae0a25c4e.png)
![XESS_blindock2](https://user-images.githubusercontent.com/117424735/203770053-2b00cdea-b70b-486e-be27-68293137a62a.png)
![XESS_blindock1](https://user-images.githubusercontent.com/117424735/203770062-10515973-3fa4-4bc9-964c-4f2d30785a3c.png)

**Comment by mdaakhan** [comment]
Fixed in Bundel V_2_1_0
