### ISSUE TITLE
Target-Ligand Interaction results is not changing 

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#113]
**PRinS_Ubuntu_20_86X64_2_0_0**

Target-Ligand Interaction results is not changing if other Binding Energy is selected. This is observed in both active site and blind docking 

![XESS_interactions](https://user-images.githubusercontent.com/117424735/203772876-957732e5-7eab-4b85-a5f2-1f00e91f751c.png)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
