### ISSUE TITLE
Simulation stops at 88% if MMPBSA is selected 

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#114]
**Machine** - PIPL03
**PRinS_V_bs_Ubuntu_20_04_x64**

1. MD simulation is not working if I select MMPBSA, it stops at 88% and shows simulation completed. I took the same complex for MD simulation without MMPBSA then it worked.
2. The estimated time was showing 13 hours however the simulation got completed in 2 hrs (2 complex for 1 ns each) 

![MD_MMPBSA](https://user-images.githubusercontent.com/117424735/203781990-3517cac3-54ec-4f20-a1a4-41d3e7eae50c.png)
![MD_EstimatedTime](https://user-images.githubusercontent.com/117424735/203782004-2e122a2c-36af-4b45-ab47-333c7cb01a4b.png)
![MD_completed](https://user-images.githubusercontent.com/117424735/203782010-9e5f4c01-5810-4d17-80ac-e7c6cda014e7.png)

**Comment by chandkc** [comment]
MMPBSA issue is resolved.
