### ISSUE TITLE
Energy Minimization error in MD Simulation

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#116]
**PRinS_Ubuntu_20_86X64_2_0_0
Machine - PIPL 03**

The simulation stop at 1% and gives **_Energy minimized configuration was not generated_** in Terminate Job section.

![XESS_MDError](https://user-images.githubusercontent.com/117424735/205624213-3d8bcfcb-6958-4ce2-8435-3e78ba0cd230.png)

**Comment by chandkc** [comment]
This set stopped at the EM step.
nvidia-smi was not loaded.

@bishweshwarShome 
Once the MD jobs are submitted, please check:
1. nvidia-smi for GPU servers;
2. gromacs sucessfully running.

This is similar to what you have done for DC.

**Comment by chandkc** [comment]
@bishweshwarShome any update?

**Comment by bishweshwarShome** [comment]
Implemented.

Commit id: 2e71e40
