### ISSUE TITLE
sdf to pdb

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#119]
PRinS_Ubuntu_20_86X64_2_0_0

1. If the **sdf ligand** filename has space or any special character (other than underscore) then it will not get converted into pdb file.
2. **converted2pdb.log** includes those sdfs also which are not getting converted into pdb. 
For example _1-Methy hydantoinCID_69217.sdf_ is not getting converted to pdb but it is seen in log file.

![XESS_log](https://user-images.githubusercontent.com/117424735/208637723-81f622da-02ef-49ec-ac3f-e5a40ad40ede.png)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
