### ISSUE TITLE
FES Average Normalization

### ISSUE THREAD

**Issue by chandkc** [chandkc/X-ESS#12]
Do we have the average on the probability or just the SUM.
In the backend, we compute the SUM only.

Needs to double check.

<img width="991" alt="Screen Shot 2022-08-16 at 1 01 51 AM" src="https://user-images.githubusercontent.com/105489779/185302816-f39793b8-4d16-4401-bff0-df04933c8990.png">

**Comment by chandkc** [comment]
@prescienceit Updated the FES averaging code.
Please see the attached file. 
Before using this file, change its extension to .py.

[test.zip](https://github.com/chandkc/X-ESS/files/9434731/test.zip)

**Comment by mdaakhan** [comment]
Fixed
