### ISSUE TITLE
user interface crashes when proceed for docking 

### ISSUE THREAD

**Issue by sujitpre** [chandkc/X-ESS#121]
After filling up the grid parameters for docking in X-ESS, when next button is clicked software user interface crashes. In the terminal , it gives e error message: "FileNotFoundError: [Errno 2] No such file or directory: '/home/sujit/Hackathon_project2/Docking/Summary/Minimum_Binding_Energy/Energy.dat'
Aborted (core dumped)
![Screenshot from 2023-01-25 20-27-20](https://user-images.githubusercontent.com/105837333/214598069-4768e39a-136b-4a12-8874-9241fe2e354a.png)
![Screenshot from 2023-01-25 20-30-05](https://user-images.githubusercontent.com/105837333/214598116-2229f40d-f4ed-46fe-9dad-21c6af43d07a.png)

**Comment by mdaakhan** [comment]
Fixed will be visible in next release
