### ISSUE TITLE
0 byte PDB in input ligand & remote directory

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#125]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x (Internal release)
**OS** - Linux

1. If the input pdb dataset have at least one pdb which is 0 byte then none of the pdbs shows on interface. This happens from sdf to pdb conversion also. The 0 byte pdbs should be removed and displayed on log.
2. While downloading the remote directory, if the combinations are a lot then the Message box doesn't scroll down and it is not downloaded because OK button is not visible in this case.

![xess3](https://user-images.githubusercontent.com/117424735/221483690-baf7a72b-9c79-4ab9-938d-ddf010b23460.png)
![xess2](https://user-images.githubusercontent.com/117424735/221483700-4a6f4eca-5475-4ce9-af3b-e7a45cf84a6a.png)
![xess1](https://user-images.githubusercontent.com/117424735/221483702-f8cbce0a-39e8-4fd8-87a7-4d311a48ac29.png)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
