### ISSUE TITLE
Plots and table for MMPBSA

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#132]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x
**OS** - Linux
**Machine** - PIPL03

 _All Proteins_ option is not working when selected for plots and table. When single protein is selected then it is working fine.

**Suggestion** - An option to download summary_mmpbsa.csv should be given when the user selects table.

![Screenshot from 2023-03-23 09-46-48](https://user-images.githubusercontent.com/117424735/227432832-f5c083bb-8345-492c-ac8b-287209a690ff.png)
![Screenshot from 2023-03-23 09-46-34](https://user-images.githubusercontent.com/117424735/227432825-21c5005e-4b3d-4f19-8bc6-9d2043f3bcb4.png)
![Screenshot from 2023-03-23 09-46-56](https://user-images.githubusercontent.com/117424735/227432814-fe843fee-3b8c-42fd-994c-f893d1e871e4.png)

**Comment by mdaakhan** [comment]
Fixed in V2.3
