### ISSUE TITLE
APO not generating

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/X-ESS#138]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x
**OS** - Linux

1. APO combination is not getting generated if the user gives only 1 complex for MD but it works if more than 1 combination are given.
2. _Download Ligand_ - If clicked on cancel button, swiss param still opens.

![apo2](https://github.com/chandkc/X-ESS/assets/117424735/6bdf8c43-f903-45a3-9879-589414592f59)
![apo_1](https://github.com/chandkc/X-ESS/assets/117424735/84b73568-6ed9-49f8-bd02-4f3984fd5eb6)

**Comment by mdaakhan** [comment]
Fixed and Commit 
c42927e..916ccdd
