### ISSUE TITLE
Docking job completed, But Docking score is not generated and Analysis window is not opening

### ISSUE THREAD

**Issue by ADHITHYA46** [chandkc/X-ESS#144]
**OS: Windows (V2.1.0)
Linux (PRinS3_V_2_1_0_Ubuntu_2020_64x)**
**Application: X-ESS (Docking)** 

**Issue:** For the protein files with missing Hydrogen atoms, Docking Jobs are getting completed and all the files are getting generated except the docking score. In the software user is unable to navigate to the analysis window.

**Suggestion**: There should be a check for input protein file to confirm whether the Missing Hydrogen atoms are added properly.

**Comment by chandkc** [comment]
@prescienceit 
If no H-bonds b/w protein and ligand, the contribution towards the docking score would be 0. Check if it is so. 
If H-Bonds=0; notify user.

**Comment by mdaakhan** [comment]
Already Solved in the previous version
