### ISSUE TITLE
Discrepancies in the HTVS job details section

### ISSUE THREAD

**Issue by ADHITHYA46** [chandkc/X-ESS#147]
**OS:** Ubuntu (2020)
**Linux** (PRinS3_V_2_1_0_Ubuntu_2020_64x)
**App**: X-HTVS

**Issue**: After the job completion on HTVS, there are discrepancies in the docking job details section.

![htvs](https://github.com/chandkc/X-ESS/assets/137476221/c5775018-71d5-4d88-8c4a-5f86413d9583)

**Comment by chandkc** [comment]
@ADHITHYA46 Are you new to this portal?

This post should be in the HTVS repository. Please post in the relavant section.

**Comment by ADHITHYA46** [comment]
Hi Sir,

Thank you for bringing this to my attention.
I apologize for the mistake. I have now posted the issue in the respective
repository for further review .
