### ISSUE TITLE
MD/FES not going ahead after docking

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#15]
Hi,

After completion of docking, MD is not going ahead.

**Comment by chandkc** [comment]
Any screenshot(s) @SumedhaBhosale ?

**Comment by SumedhaBhosale** [comment]
![XESS_MD_Topology](https://user-images.githubusercontent.com/105902516/186104866-7449a7a4-8cb5-4546-b82a-4f1a7111f71f.png)

**Comment by SumedhaBhosale** [comment]
After reloading project directory, 'Upload' button gets enabled but Job fails to run. While Apo-simulation job started running.

![MD_Topology_2](https://user-images.githubusercontent.com/105902516/186112106-3a390403-de03-415a-bf59-e1389b6d85b7.png)

**Comment by SumedhaBhosale** [comment]
Apo-simulation job stucks at 2%.

**Comment by mdaakhan** [comment]
Fixed With Commit ID: 986de25
