### ISSUE TITLE
PIPL03- Molecule view-Core dumped

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#2]
**software- v2_test
machine- PIPL03**

When setting up the database for docking, if we click on the target or ligand names for molecule view, software crashed & core dumped.
![molecule view_crash](https://user-images.githubusercontent.com/111036161/184073990-704728e2-0d80-43d2-8ce0-df41c108e4f6.JPG)

**Comment by mdaakhan** [comment]
According to Aishwarys Visualizer is working in PIPL03, and will have to check the main issue in PIPL03

**Comment by mdaakhan** [comment]
System Specific Error for visualizer will have to recreate it
