### ISSUE TITLE
'Next' button in Docking - Not working

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#20]
Hi,

I submitted few jobs using active site docking option. Jobs got completed but 'Next' is not working. I cannot visualize the docking analysis plot. 

EXE dated 27 Aug
Linux machine

![Docking_Next](https://user-images.githubusercontent.com/105902516/187078815-0ff8b497-cf91-4e9b-9bb7-2a7415cd5040.png)
 
![Docking_Terminal](https://user-images.githubusercontent.com/105902516/187079163-72e78675-a3a9-4761-9750-5e2f962dcc56.png)

**Comment by LobeliaG** [comment]
Same thing happening with the Windows .exe as well.

**Comment by mdaakhan** [comment]
Fixed in D_V_0_5
