### ISSUE TITLE
ubuntu V2_3 new project

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#21]
new project directly takes you to select combinations for MD
PIPL03 machine
27 Aug exe ubuntu V2_3

<img width="1229" alt="Screen Shot 2022-08-28 at 5 33 00 PM" src="https://user-images.githubusercontent.com/105898169/187097250-e4540869-c503-41a0-a7d5-606773624492.png">

**Comment by mdaakhan** [comment]
Fixed in New EXE
