### ISSUE TITLE
Docking no output Ubuntu V2_3 PIPL03

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#22]
after performing docking ui says alert analysis of docking combination could not be calculated.
PIPL03 machine
27 Aug exe ubuntu V2_3
<img width="1046" alt="Screen Shot 2022-08-28 at 6 49 16 PM" src="https://user-images.githubusercontent.com/105898169/187099910-c758ad35-9245-4465-8c06-8097889d8039.png">

**Comment by LobeliaG** [comment]
PIPL01
TEST_V2_3- windows version. Same issue encountered.
![image](https://user-images.githubusercontent.com/111036161/187139122-84f55c03-984e-401a-aa16-61828855c2ac.png)

**Comment by mdaakhan** [comment]
@LobeliaG please check the GMX setting in the data connector it should be 2021 
@aiswaryapawar I have checked in the PIPL03 Container was V2 while in the data connector GMX was 2018 due to this it is throwing error implementing the additional checks for the version Keeping this issue open till the check was implemented

**Comment by LobeliaG** [comment]
> @LobeliaG please check the GMX setting in the data connector it should be 2021 @aiswaryapawar I have checked in the PIPL03 Container was V2 while in the data connector GMX was 2018 due to this it is throwing error implementing the additional checks for the version Keeping this issue open till the check was implemented

It is 2018 in PIPL01 @prescienceit 
![image](https://user-images.githubusercontent.com/111036161/187182929-60468b64-40d6-47d5-a39a-3cf8c4691b4e.png)

**Comment by mdaakhan** [comment]
change it to gmx_2021
and in the gromacs path 2021 in place of 2018, 
save it and reload the software it will work fine then.

**Comment by LobeliaG** [comment]
> change it to gmx_2021 and in the gromacs path 2021 in place of 2018, save it and reload the software it will work fine then.

Yes data analysis is available now. Thanks.
