### ISSUE TITLE
TEST_V2_3 - 'NEXT' button shows inaccurate information 

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#24]
machine-PIPL01
software- windows version
In Docking job details window, the 'next' button below should take us to the data analysis part. But on hovering over the option it shows it will take us to MD.

![image](https://user-images.githubusercontent.com/111036161/187135576-4c695b84-0abf-4c65-8508-db0e4516a80e.png)

**Comment by mdaakhan** [comment]
Fixed in D_V_0_5
