### ISSUE TITLE
PIPL01- issue in selection of combinations for MD 

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#25]
machine-PIPL01
software- TEST_V2_3- windows

After docking analysis, upon changing the cut off value for selection, the chosen set of combinations for MD does not update. All of the combinations are there already even before selecting.

![image](https://user-images.githubusercontent.com/111036161/187194112-01b007f5-142a-4199-91c5-4047c0ac779d.png)
![BE](https://user-images.githubusercontent.com/111036161/187194268-d968cf23-e117-45ba-8cda-b4ef1429bbc4.JPG)

**Comment by mdaakhan** [comment]
Fixed in D_V_0_4
