### ISSUE TITLE
PIPL01- TEST_V2_3- issue in docking Interaction view image export

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#26]
machine- PIPL01
windows version- TEST_V2_3

Here in docking data analysis, the export of the shown image could not be completed.

![image](https://user-images.githubusercontent.com/111036161/187360226-ff3f7d7e-3d96-4d3f-9bdf-28a3391727d6.png)

**Comment by mdaakhan** [comment]
@LobeliaG  check-in this V_D_2_7 release if the issue persists we can reopen the issue.
