### ISSUE TITLE
v2- Docking- software crashed

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#3]
**machine- PIPL03
version- v2_test**

Software crashes during preprocessing. Terminal snapshots are attached.

![terminal- docking crashed](https://user-images.githubusercontent.com/111036161/184075462-633f2080-ab32-4918-b93f-9229a150bd99.JPG)
![docking_crashed1](https://user-images.githubusercontent.com/111036161/184075454-67c023c9-39bd-4820-a161-e230254977c4.JPG)
![docking_crashed2](https://user-images.githubusercontent.com/111036161/184075458-9f4db5f0-543c-41bf-9815-0bb7705de818.JPG)

**Comment by mdaakhan** [comment]
GUI ISSUE, System Specific, will try to recreate it (Working now in PIPL03)
