### ISSUE TITLE
PIPL01 - issues in updating the Force field path

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#30]
windows version- TEST_V2_3

After making a selection of combinations for MD, next we go for force field generation. However if we change our mind after entering the force field path, and we go back and make changes in the selected combinations, when we try to update the force field path and MOL file & ITP file paths for them they do not get updated. And the upload button remains disabled.

![image](https://user-images.githubusercontent.com/111036161/187497486-7500a190-4afc-419f-9862-b93f4a4be368.png)

**Comment by mdaakhan** [comment]
Fixed in new version

**Comment by LobeliaG** [comment]
ubuntu- TEST_V2_7

The problem was again noticed. Here I went back, changed the selected combinations from 2 to 1, came back and uploaded the force field path, but upload button remains disabled.
![image](https://user-images.githubusercontent.com/111036161/189835572-ef986c67-8a24-4c7d-b0a3-239089a14c0a.png)

Can we not put a refresh option in this page?

**Comment by mdaakhan** [comment]
@LobeliaG We can sit to see this error unable to recreate this error

**Comment by mdaakhan** [comment]
Fixed in commit 88fdc8e date October 10
