### ISSUE TITLE
Alert - "Docking could not be completed" - Pop-up message after docking completion

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#31]
Hi,

Exe shared on 27 Aug - [TEST_V2_3]
 Windows machine

After docking completion, this pop-up comes even if docking for the combination is completed. Please check the screenshot attached (_check specifically row number 4 combination_). 

![XESS_Docking_AlertPop-up](https://user-images.githubusercontent.com/105902516/188069959-a6212db9-15f4-4fe5-98e4-8b19f7595028.PNG)

**Comment by mdaakhan** [comment]
@SumedhaBhosale  Please check in new exe

**Comment by mdaakhan** [comment]
Fixed in commit 88fdc8e date October 10
