### ISSUE TITLE
One combination in docking - Not getting ahead for docking. No error thrown for the same. 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#32]
Hi,

Windows machine
Exe shared on 27 Aug - [TEST_V2_3]

I submitted four combinations for docking. three of them got transferred to the server and docking ran for them. Due to some reason, one of them couldn't went further. 'Docking Job details' display information as 'status not available'. But as such no error is thrown for same. Combination files also are not transferred to IO DIR. How would the user know what is wrong with combination ? for e.g. is their a problem with atoms or PDBQT is not generated or map files are not getting generated.

![XESS_Docking_StausNA](https://user-images.githubusercontent.com/105902516/188075306-19892271-021a-41bf-a62f-0e91befb0508.PNG)

**Comment by SumedhaBhosale** [comment]
Input Files
[Protein_LIG_Input.zip](https://github.com/chandkc/X-ESS/files/9475535/Protein_LIG_Input.zip)

Binding Site residues
345,256

**Comment by SumedhaBhosale** [comment]
Tried one more time with same input files - Now all jobs got stuck at 40 %. 
Done on same machine with same exe. 

Attaching screenshot

![XESS_Docking_StausNA_StuckAt40](https://user-images.githubusercontent.com/105902516/188108641-0ee280ca-0d76-444a-824b-ef6101218e5b.PNG)

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1
will be reflected in V_D_2_7
