### ISSUE TITLE
FES stuck & issues in MD data analysis section 

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#33]
**Machine- PIPL01
software windows version- PRiNS_D_V_2_0_4**

After testing the software with the provided sample complex structures, MD got completed, But following errors were noticed-
1. Even on selecting MMPBSA option before running MD, the data is not displayed in analysis.
![MMPBSA](https://user-images.githubusercontent.com/111036161/188298326-0059dcc5-f1a5-4f79-91fd-235ba0291b68.JPG)

2. H-bonding groups table remains blank
![MDbondinggroups_empty](https://user-images.githubusercontent.com/111036161/188298339-3e895b12-cc67-469b-b192-d399ef0be306.JPG)

3. FES does not get ahead. 
![image](https://user-images.githubusercontent.com/111036161/188298346-26679740-4572-4978-8dc4-487de780d747.png)

The path to the project folder in this case- D:\Lobelia\Complextest_DV204
Path to IO directory files- D:\Lobelia\IO\PIPL\MTML (**No FES job files are generated**)

**Machine- VDI- prescience1
same software Ubuntu version**
1. here I went ahead with 1 complex and the associated APO complex instead of 2 sample structures. After MD however, the plot for H bond was showing both my selected and unselected complexes.
![Screenshot from 2022-09-02 20-49-05](https://user-images.githubusercontent.com/111036161/188298853-d57116bb-3e87-40ac-803f-56a9bb284cf0.png)
![Screenshot from 2022-09-02 20-54-08](https://user-images.githubusercontent.com/111036161/188298874-5929b7f6-d826-4277-9ddd-c796f8b7a47c.png)
2. H-bonding groups table was empty here as well.
![Screenshot from 2022-09-02 20-56-41](https://user-images.githubusercontent.com/111036161/188298918-dd7f4ebf-6543-400f-92c4-d0f90241045b.png)
3. FES did not work here as well.
![Screenshot from 2022-09-02 22-24-32](https://user-images.githubusercontent.com/111036161/188298947-8e511f7c-1b5d-4b64-9b69-30a2c3738aa3.png)
Here is the terminal snapshot-
![Screenshot from 2022-09-04 10-53-21](https://user-images.githubusercontent.com/111036161/188298968-e258f2dc-a632-48ad-9c63-0ca333d31609.png)

Path to project directory-/home/YOTTAVDI/prescience1/Prins_nEW/Complextest_DV204
path to IO directory- /home/YOTTAVDI/prescience1/Prins_nEW/Softwares/DV202_IO_DIR

**Comment by SumedhaBhosale** [comment]
Hi,
I tried with input files shared by @prescienceit. MD works and graphs can be visualized except result for MM-PBSA. 

FES doesn't go ahead.

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1
will be reflected in V_D_2_7
