### ISSUE TITLE
complex MD results not downloading

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#36]
Ubuntu machine-PIPL03
exe- Test_V2_4(shared on sep2)

one complex structure uploaded and ran MD for 1ns, after the run was complete. the MD data did not download. it gives an error for apo as well complex structure. please refer to the screenshot. 
<img width="1066" alt="Screen Shot 2022-09-05 at 10 16 18 PM" src="https://user-images.githubusercontent.com/105898169/188541605-be5e64d7-023b-4eac-bb1c-80afe0f7002e.png">
[pink1-D309_test15.pdb.zip](https://github.com/chandkc/X-ESS/files/9493261/pink1-D309_test15.pdb.zip)(unzip the input file)

**Comment by LobeliaG** [comment]
**Windows machine -PIPL01
exe- Test_V2_4**
Same problem encountered.
Another complex structure, other than the provided sample structures was uploaded and ran MD for 1ns. After run, the MD data did not download. it gives an error for apo as well complex structure. 
![MDdownload_fail](https://user-images.githubusercontent.com/111036161/188542536-a1e2de5a-49f9-4a1b-9008-2e786d5d5dec.JPG)
![MDdownloadfail](https://user-images.githubusercontent.com/111036161/188542545-a3195785-135f-4de3-aeef-85360b7a15b1.JPG)

**Comment by LobeliaG** [comment]
When I tried with the same complex input with 0.1ns NPT simulation time, the data got downloaded.

**Comment by mdaakhan** [comment]
Tested and Checked Working for 1ns @LobeliaG please check it again in new version expected to be released today
