### ISSUE TITLE
RMSD results same for whole protein and binding site

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#37]
Ubuntu machine-PIPL03
exe- Test_V2_4(shared on sep2)

Ran complex and apo simulations, and the RMSD results for both complex and apo for whole protein and the binding site look the same. 
<img width="1068" alt="Screen Shot 2022-09-05 at 6 52 34 PM" src="https://user-images.githubusercontent.com/105898169/188542437-5f79d855-ad91-45bf-9eb0-55ec8ffb7c98.png">
<img width="1058" alt="Screen Shot 2022-09-05 at 6 52 43 PM" src="https://user-images.githubusercontent.com/105898169/188542455-4f98e2f9-d374-4212-889e-abbe15b8bd22.png">

**Comment by chandkc** [comment]
@LobeliaG In the maunal, please advise the user to use a shorter file name when they upload the complex. If not, the plots would look as above.

**Comment by LobeliaG** [comment]
> @LobeliaG In the maunal, please advise the user to use a shorter file name when they upload the complex. If not, the plots would look as above.

okay sir

**Comment by mdaakhan** [comment]
Fixed
