### ISSUE TITLE
Input to Complex Structure

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#38]
While we give input to Complex structures, it's taking file name as protein as well as Ligand. This might be confusing. 

Attached screenshot for reference here - 

![XESS_InputFilesNaming](https://user-images.githubusercontent.com/105902516/188779527-57292dc3-3e6b-4ba2-88c8-7f87263b92b1.png)

**Comment by SumedhaBhosale** [comment]
Also, Observed this where protein was same only named differently, But it is taken twice for Apo-simulation based on File Name. 

![XESS_CombinationsNaming](https://user-images.githubusercontent.com/105902516/188779867-d39a7613-3cbf-4363-9da2-7a735522b7ce.png)

**Comment by chandkc** [comment]
Esp. in case of Complex MD: we do not know the name of the LIGAND, as a separate ligand file is not uploaded.
So, to distinguish between protein and ligand, we prefix the user uploaded file name with p and l, respectively.

**Comment by chandkc** [comment]
***@LobeliaG For Manual. Complex MD Section. Convention for protein and ligand while filtering. ***
User uploads the protein bound ligand. Separate ligand file is not required. 
So, to distinguish between protein and ligand, we prefix the user uploaded file name with _p_ and _l_, respectively.

**Comment by chandkc** [comment]
closed
