### ISSUE TITLE
Blind Docking 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#4]
1. Visualizer is not displaying grid box. To check whether box is filling whole protein or not, it is mandatory to display box !

![XESS_BlindDock_Visualizer](https://user-images.githubusercontent.com/105902516/184169207-a5c6064f-da7e-4463-9ac8-96cb75cc2c05.jpg)

**Comment by mdaakhan** [comment]
Sumedha in the blind docking box is not displayed it is developed accordingly according to the discussion while the time of development, if it is required we can discuss and get it implemented.

**Comment by chandkc** [comment]
We do not have grid information in the grid parameter section. So, box cannot be displayed.
