### ISSUE TITLE
'Blind Docking Output' tab - 'Select' - selects more than one fill/binding site

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#40]
Hi,

Windows machine
Version 5 shared on 8 Sep

As of now, user can select more than one binding sites from 'Select' in Blind Docking Output tab in XESS. It should be strictly one. 

![XESS_SelectOptions](https://user-images.githubusercontent.com/105902516/189073331-90cd6f58-4ef3-4580-8c3d-2f3f13bbd9aa.jpg)

**Comment by mdaakhan** [comment]
Multiple selections is enabled so that the user takes multiple conformations for the docking as discussed with the sudip sir

**Comment by SumedhaBhosale** [comment]
Hi,

But this the binding site residues we are choosing here so how can we do multiple binding site docking ?

**Comment by chandkc** [comment]
1. Binding site is predicted by Autodock.
2. Based on the FILL, the binding site can be selected.
3. User can choose the binding sites based on the volume or the binding energy.
4. So, we are giving multiple option. This will als enable user to see how the other binding sites perform from the Autodock energies, by docking with higher number of GA runs.

I am not closing this issue now. We can discuss this with @aiswaryapawar as well in the morning.

**Comment by SumedhaBhosale** [comment]
Okay sure.
