### ISSUE TITLE
Blind Docking - 'Select' from Target-Ligand Interaction Profile doesn't work. 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#41]
Hi,

Windows machine
Version 5 shared on 8 Sep 

'Select' from 'Target-ligand interaction profile' doesn't work. 

![XESS_Select_NoWork_TLI](https://user-images.githubusercontent.com/105902516/189074101-db42dc8f-f0be-4b15-8e63-23ccbe561b5d.jpg)

**Comment by SumedhaBhosale** [comment]
Hi,

Tried this in Version 6 shared in the 8 Sep evening. 
Windows machine

Same problem persists. LIP  doesn't update with each conformation using **'Select'** at the right hand side (see screenshot from above comment). LIP updates only with ligand name using **'Select Combination'**

**Comment by mdaakhan** [comment]
Fixed in V2
