### ISSUE TITLE
Binding Energy and Binding Score Graphs - Looks alike. 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#42]
Hi, 

Machine - Windows
Exe - V2_6 shared on 8 Sep afternoon. 

Binding Score and Binding Energy graphs looks same. Attaching screenshots of both graphs along with summary file - which exact displays values. 

Summary File - Check Values for docking energy (Ranging from **-5**- to **-9**) and docking score (Ranging from **-3** to **-6**) 
![XESS_Summary](https://user-images.githubusercontent.com/105902516/189130896-fc3b0f2c-5a53-4640-a769-d5bb36268021.jpg)

Binding Energy aka Docking Energy Graph
![XESS_BE](https://user-images.githubusercontent.com/105902516/189130935-99f1b598-083e-4f2d-9f34-988f4c991e6e.jpg)

Binding Score aka Docking score Graph
![XESS_BS](https://user-images.githubusercontent.com/105902516/189130965-3123cc0d-5cae-4215-bfa1-606accc2f642.jpg)

Input Files - First Blind docking was done - Fill number 3 and 7 were chosen to go ahead for normal/active site docking.  
[XESS15.zip](https://github.com/chandkc/X-ESS/files/9527077/XESS15.zip)

**Comment by aiswaryapawar** [comment]
facing the same issue on 
Ubuntu machine- PIPL03
V2_5 exe
<img width="1054" alt="Screen Shot 2022-09-08 at 8 19 38 AM" src="https://user-images.githubusercontent.com/105898169/189152227-345e0871-ea85-46d1-96a7-afe75eebecc8.png">
<img width="1052" alt="Screen Shot 2022-09-08 at 8 19 43 AM" src="https://user-images.githubusercontent.com/105898169/189152230-03642159-ae21-483b-ba1c-534388198599.png">

**Comment by LobeliaG** [comment]
machine- PIPL01
Windows- TEST_V2_6

Same problem faced. Docking energy and docking score graphs looks the same after execution of blind+active docking.
![image](https://user-images.githubusercontent.com/111036161/189284827-2524ae9a-ea94-428d-aa9f-d751a88c9b6e.png)
![image](https://user-images.githubusercontent.com/111036161/189284963-b786f858-b5c0-4888-bbd5-f78331d2267d.png)

**Comment by SumedhaBhosale** [comment]
Hi,

V2_8 exe shared on 13 Sep. 
Issue still persists ! 

![XESS21_BE](https://user-images.githubusercontent.com/105902516/190103673-70d3dfe1-23cf-4ba3-829b-d0425135222a.jpg)

![XESS21_BS](https://user-images.githubusercontent.com/105902516/190103695-a900f86e-0aa5-4faf-a02d-cf6f75954fe2.jpg)

**Comment by SumedhaBhosale** [comment]
Hi,

PRinS_Hackathon_Sep_Windows EXE
Windows machine

Problem still persists ! 
![XESS22_BE](https://user-images.githubusercontent.com/105902516/190344087-596c1a54-e438-46e7-838a-2287e15b032a.jpg)

![XESS22_BS](https://user-images.githubusercontent.com/105902516/190344098-85f9c95b-56ef-4134-96a3-eab7ad1ea226.jpg)

**Comment by mdaakhan** [comment]
Fixed
