### ISSUE TITLE
'Upload' - Not getting enabled. 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#43]
Hi,

Windows machine
V2_6 exe

'Upload' at Ligand topology not enabled. After reloading project, it gets enabled. Discussed with @prescienceit 

![XESS_MD_Upload](https://user-images.githubusercontent.com/105902516/189138619-8771d369-6ebf-46b6-919f-1274d3990db0.jpg)

**Comment by SumedhaBhosale** [comment]
Hi,

Windows machine
V2_6 exe 

In case of 'Browse Complex Structures', 'Upload' is not getting enabled too. Reloading project directory, makes no difference. Please check.

**Comment by mdaakhan** [comment]
Unable to produce this error if this error occurs in this release will sit in the same project and reopen the issue till that time closing the issue

**Comment by SumedhaBhosale** [comment]
Hi,

Ubuntu machine
V_2_8 exe shared on 16 Sep

Struggling with 'Upload' to get enabled.  

My guess to re-create the scenario - Take inputs in complex structure, go ahead and then come back modify the list (leave 1 or 2 combinations), upload the zip files and see if 'Upload' button is getting enabled. 

I could see list of combinations twice when I reloaded the project directory. Screenshot attached. 

![XESS_Upload](https://user-images.githubusercontent.com/105902516/191902445-561becf2-35d3-49b0-81a9-12c789e42b62.png)

**Comment by mdaakhan** [comment]
Fixed in commit 88fdc8e date October 10
