### ISSUE TITLE
'Cut-off' of docking energy not working

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#44]
Ubuntu machine- PIPL03
V2_6 exe

the cutoff while proceeding to docking not working, i have selected the conformations from the target-ligand interaction and then proceeded to provide cut-off for docking. 
<img width="1076" alt="Screen Shot 2022-09-08 at 9 37 42 AM" src="https://user-images.githubusercontent.com/105898169/189151911-bff870d3-25d8-46b3-88a8-110124165ded.png">
<img width="1045" alt="Screen Shot 2022-09-08 at 9 32 54 AM" src="https://user-images.githubusercontent.com/105898169/189151932-22dffa89-7f44-4b45-8737-809b9fc6eb0f.png">
<img width="897" alt="Screen Shot 2022-09-08 at 9 42 15 AM" src="https://user-images.githubusercontent.com/105898169/189152025-55a7bf40-b42a-4f3e-a557-f7b78dbdfada.png">

**Comment by LobeliaG** [comment]
**Windows machine- PIPL01
software- PRiNS_D_V_2_0_6**

Similar problem. Cut off for selection of combinations for MD has some glitch. Not able to to select the complexes correctly.
![combos](https://user-images.githubusercontent.com/111036161/189174477-7f927c1f-2913-49a2-afde-c92a1a68151e.JPG)
![image](https://user-images.githubusercontent.com/111036161/189174406-c10545cd-c194-4708-bc3b-9652cb25d1e0.png)
![complex2](https://user-images.githubusercontent.com/111036161/189174609-882c1506-9bbb-4fb9-a196-e73e366b4467.JPG)

**Comment by SumedhaBhosale** [comment]
Hi,

Faced the same issue. 

Windows machine
V2_6 Exe

In case of 'Active Site Docking', where we provide binding site residues, at the time of selection of combinations to go further for MD, I choose particular conformations from 'Docked Pose' tab, but they are not getting selected. 

![XESS_ActiveSiteDocking_SelectCombi](https://user-images.githubusercontent.com/105902516/189254706-3fa0f665-7148-4358-a051-fe641b16fe45.jpg)
