### ISSUE TITLE
RMSD for Apo shown for binding site

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#45]
Ubuntu machine- PIPL03
V2_6 exe
Module- Active docking
RMSD shown for apo binding site when you select target as all proteins

<img width="1069" alt="Screen Shot 2022-09-08 at 8 42 32 PM" src="https://user-images.githubusercontent.com/105898169/189254731-2f1efaab-8670-40c8-8337-a532dd240c5f.png">
<img width="1057" alt="Screen Shot 2022-09-08 at 8 42 39 PM" src="https://user-images.githubusercontent.com/105898169/189254734-e30ddc91-e504-4ed9-99cd-fa95789b05d6.png">

**Comment by mdaakhan** [comment]
Fixed and will take effect in next demo release
