### ISSUE TITLE
No COM distance displayed

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#46]
Ubuntu machine- PIPL03
V2_6 exe
Module- Active docking
no plot displayed for COM in MD, also there are 3 ligands and only one ligand shown in x axis

<img width="1056" alt="Screen Shot 2022-09-08 at 8 49 00 PM" src="https://user-images.githubusercontent.com/105898169/189255348-2e4b40b4-dc74-4778-8df6-8d273dcd6d1c.png">

**Comment by LobeliaG** [comment]
Windows machine- PIPL01
software- V2_6 exe
No plot displayed for COM in MD.
![image](https://user-images.githubusercontent.com/111036161/189265829-d3f6bcc1-17f5-4ca6-83fd-2fa49fe68c60.png)

**Comment by mdaakhan** [comment]
@aiswaryapawar Active or blind Docking

@prescienceit For active docking
still this issue there in version V2_7
thats why cant perform FES
<img width="1063" alt="Screen Shot 2022-09-10 at 1 05 07 PM" src="https://user-images.githubusercontent.com/105898169/189496123-9d360e95-9801-49a8-b32e-c5d522c44d82.png">

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1 
will be reflected in V_D_2_7
