### ISSUE TITLE
No combinations for FES 

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#47]
Ubuntu machine- PIPL03
V2_6 exe
Module- Active docking
no combinations displayed before proceeding to FES
<img width="918" alt="Screen Shot 2022-09-08 at 8 51 27 PM" src="https://user-images.githubusercontent.com/105898169/189255716-fed83a28-4a1b-41de-bc83-c1425c58272a.png">

**Comment by SumedhaBhosale** [comment]
hi ,

Window machine
V2_6 exe 

Facing Same issue

**Comment by SumedhaBhosale** [comment]
Hi,

Windows machine
V2_7 EXE shared on Fri 9 Sep

Combinations are not going ahead for FES after "Browse complex Structure" option (MM-PBSA was ran; 1ns NPT). Please check

![XESS19_FESCombination](https://user-images.githubusercontent.com/105902516/189589852-bf7fdb50-f58a-4ab6-a808-dab8970de4a9.jpg)

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1 
will be reflected in V_D_2_7
