### ISSUE TITLE
Information needed on help button

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#48]
software windows version- TEST_v2_07

The help/? button here in complex input part shows no information on hovering over it.  Please put some information about the required input file here.
![image](https://user-images.githubusercontent.com/111036161/189420249-456a6fd0-8a1a-4545-a462-5c978833687e.png)

**Comment by chandkc** [comment]
A protein-ligand complex (protein bound with a ligand) can be uploaded here. This complex will directly go to the MD stage.
The ligand in the pdb file MUST be identified with the LIG or UNK as the residue name.

**Comment by mdaakhan** [comment]
Fixed in V2
