### ISSUE TITLE
APO combination doesn't download in MD

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#49]
Ubuntu V2_7 PIPL03 machine
Module- Active docking
The Apo combination doesn't download after  MD completion and gives an error. 

<img width="767" alt="Screen Shot 2022-09-09 at 6 10 32 PM" src="https://user-images.githubusercontent.com/105898169/189457481-99e3815d-882d-43dc-959b-baad442e4650.png">

**Comment by LobeliaG** [comment]
windows machine- PIPL01
**software- TEST_V2_7
MD with Complex inputs**
APO combinations did not get downloaded after MD.

![image](https://user-images.githubusercontent.com/111036161/189567197-8b0e2e8a-adb9-4e28-8c1d-986f5d5d97aa.png)
![downloadfail1](https://user-images.githubusercontent.com/111036161/189567239-e4104b52-a847-425e-a5b0-2744f372151a.JPG)

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1 
will be reflected in V_D_2_7
