### ISSUE TITLE
Hydrogen bond error

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#50]
Ubuntu PIPL03 machine
Version V2_7
Module- Active docking
Hydrogen bond after the MD completion, in MD job details shows no hydrogen bond information.
But the plot and hydrogen bond group shows there is one hydrogen bond formation. 
<img width="1055" alt="Screen Shot 2022-09-10 at 1 00 32 PM" src="https://user-images.githubusercontent.com/105898169/189496085-047ded67-9219-4ac1-9d11-45d7a9317aaa.png">
<img width="1058" alt="Screen Shot 2022-09-10 at 10 52 50 AM" src="https://user-images.githubusercontent.com/105898169/189496086-9cb786d3-86b2-4d42-8674-dc5561e82091.png">
<img width="1079" alt="Screen Shot 2022-09-10 at 10 52 59 AM" src="https://user-images.githubusercontent.com/105898169/189496087-d74b99b6-08fe-4a7c-b66a-9abc79dd678e.png">

**Comment by mdaakhan** [comment]
@chandkc Need your help

**Comment by chandkc** [comment]
Following scenarios are implemented to compute and show H-Bonds:

1. MD trajectories are split in 5 parts from the last  half of the trajectory.
2. Hydrogen bonds are computed, separately, in these parts.
3. If any of the part(s), doesnot have hydrogen bond, we throw an error in the UI saying that Hydrogen bond is not found.

4. In the local, the hydrogen bond data from these 05 parts are accumulated and are shown in the UI in the form of table and plots.

6. The hydrogens bond table doesnot indicate anything if we donot have consisten number of HB in each part?
Q1.. Should we show a HB vs. time?
Q2. We can show average HB as well?

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
