### ISSUE TITLE
MM-PBSA : Plots showing wrong X-axis range

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#51]
Hi,

Windows machine
V2_7 Exe shared on Friday 9 Sep

Tried MM-PBSA using "Browse Complex Structure" option. NVT was reduced to 0.005 ns while NPT was for 1 ns. Software estimated almost 14 hours for only one combination. @chandkc How are we estimating time for XESS ? 

Upon completion, graphs for Free energy (MM-PBSA) could be visualized along with values in table. @chandkc How are we estimating time for XESS

Although found small thing in plots which is plotted X-axis range (960 ns to 1040 ns). 

Screenshots attached as follows - 

![MMPBSA_YAXIS_3](https://user-images.githubusercontent.com/105902516/189587765-2f55a26c-ac5a-4126-8064-89b31bc66766.jpg)

![MMPBSA_YAXIS_2](https://user-images.githubusercontent.com/105902516/189587804-a7b3cd60-e753-4b54-9ada-dd5a0bca826b.jpg)

![MMPBSA_YAXIS](https://user-images.githubusercontent.com/105902516/189587846-3a8cb177-b268-41c8-a0d4-502cb78d1ab3.jpg)

**Comment by mdaakhan** [comment]
Fixed commit id d3c21f1
