### ISSUE TITLE
'Summary file' from 'Download' after MD results : No content written 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#52]
Hi,

Windows machine
V2_7 version shared on Fri 9 Sep

The summary file we download at the end of MD is not showing any data. Please check. 

![XESS19_Summary](https://user-images.githubusercontent.com/105902516/189588532-9d023b87-2b4a-423a-8f48-3e7d4061c244.jpg)

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1
will be reflected in V_D_2_7
