### ISSUE TITLE
Input option becomes disabled for docking

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#53]
machine- PIPL03
ubuntu software- TEST_V2_7

after creating project directory, if we mistakenly **click on the Browse complex structure** option and **then after canceling** that, try to go for **Input target & ligand options for docking**, they become disabled.

![image](https://user-images.githubusercontent.com/111036161/189802930-2f46919f-f766-4f50-b606-e3549859cd2f.png)

**Comment by mdaakhan** [comment]
@LobeliaG  it is a feature once you click on the Complex structure, Protein and Ligand will be disabled. 
moreover, i will try to fix on cancel button issue

**Comment by LobeliaG** [comment]
> 

Okay sir

**Comment by mdaakhan** [comment]
fixed commit id d3c21f1
will be reflected in V_D_2_7
