### ISSUE TITLE
MM-PBSA : WCA Energy

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#57]
Hi,

Are we calculating WCA energy from non-polar components ? @chandkc 

![MMPBSA_Output](https://user-images.githubusercontent.com/105902516/189882537-e19a551f-8d9c-4c4f-85bc-ec8499d3e3bd.jpg)

**Comment by SumedhaBhosale** [comment]
Also, are we not providing bonded energy value here ?

**Comment by chandkc** [comment]
There are only two options to compute the non-bonded energy:
(a) solvent accessible surface area (SASA) model only
(b) solvent accessible volume (SAV) only

WCA is not implemented.

**Comment by chandkc** [comment]
As the bonded components do not change in simulations, the bonded energy is constant and thus the change in bonded energy is 0. So, it is not calculated.

**Comment by SumedhaBhosale** [comment]
Okay !
