### ISSUE TITLE
PIPL01-Next option disabled after MD

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#58]
machine-PIPL01
windows- TEST_V2_7

The APO downloads were failing but the two complexes got downloaded. The log window also shows jobs are done and can proceed to data analysis. But the next button remains available. even if I clear the two incomplete APO jobs the same thing happens.
Refreshed multiple times.
simulation time was 1ns and MM PBSA was selected. The jobs took 3.5 days to run.

![image](https://user-images.githubusercontent.com/111036161/189889514-5e83206e-8fb6-406b-9f97-869f9b8edeb6.png)

**Comment by mdaakhan** [comment]
@LobeliaG  Please let me know once this occurs again in your system will sit and check
