### ISSUE TITLE
FES add runs not working

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#59]
Machine- Ubuntu PIPL03
Version- V2_7
Module- Complex docking

After the FES run, i tried to add one more run. log states the signal sent but no FES run has been generated. Even the folder look empty.

<img width="1153" alt="Screen Shot 2022-09-13 at 11 37 57 AM" src="https://user-images.githubusercontent.com/105898169/189958140-e5d74ff2-41bf-434b-8454-1f7b76b6e9c5.png">
<img width="1242" alt="Screen Shot 2022-09-13 at 11 38 07 AM" src="https://user-images.githubusercontent.com/105898169/189958160-b081e959-4c82-4c1f-8029-c72aad3cd0c3.png">

**Comment by mdaakhan** [comment]
Already Solved in the previous version
