### ISSUE TITLE
MD analyse: Re-analysing the whole project directories

### ISSUE THREAD

**Issue by chandkc** [chandkc/X-ESS#6]
2 jobs are in the job table. But the analysis happens on all the previous job combinations in the same project.

![Screen Shot 2022-08-11 at 6 27 47 PM](https://user-images.githubusercontent.com/105489779/184198472-567d7921-7faf-4c90-9a83-9c0938baebfc.png)

**Comment by chandkc** [comment]
for v1

**Comment by chandkc** [comment]
Scenario:
1. Couple of combinations runs are complete. All analysis done.
2. User submitted couple of more combinations.
If the analysis in combinations of 1 were done, we should redo when the new combinations were submitted.

**Comment by mdaakhan** [comment]
Given the option to reanalysis in V2.
