### ISSUE TITLE
Issue in selection of combinations for MD

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#60]
PIPL01
TEST_V2_8- windows

Binding energy for the Complex1 combination is -5.35. Still it is not taking it even after setting the cut off at +2. Cut off is working for the default combinations. Active site docking was performed.

![image](https://user-images.githubusercontent.com/111036161/190072709-e4930b90-b383-42e7-8722-9e7f3cf1ef42.png)
![image](https://user-images.githubusercontent.com/111036161/190073362-7c4aa7bf-890c-4d79-83f6-15e471b8b604.png)

**Comment by mdaakhan** [comment]
@LobeliaG it is adding it, is showing the combination name in place of complex
