### ISSUE TITLE
BlindDocking and Docking: Status NA in Job Details 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#61]
Hi,

PRinS_Hackathon_Sep_Windows EXE
Windows machine

Input file - 
[XESS22.zip](https://github.com/chandkc/X-ESS/files/9572872/XESS22.zip) 
I choose two fills from blind docking (Fill 3 and 8), while transferring job, Job with Fill 3 could not transferred but with Fill 8 got completed. So I cleared job with Fill 3 and started again. (Sorry ! Do not have screenshot so sharing information printed in Logs)
Now, my earlier completed job with Fill 8 disappeared from Job details. 

![XESS22_BlindDocking_ClearJob](https://user-images.githubusercontent.com/105902516/190342938-a7b5af9f-0ece-4352-9fc0-2bd9eef12c93.jpg)

[Log.zip](https://github.com/chandkc/X-ESS/files/9572908/Log.zip)

But output can be seen for both !

**Comment by chandkc** [comment]
obsolete
