### ISSUE TITLE
Icon and Button size enhancement

### ISSUE THREAD

**Issue by gurdev7** [chandkc/X-ESS#62]
The ticks, fonts look small. The "Proceed to Docking" button may be separated from the block.
<img width="881" alt="Screenshot 2022-09-15 at 1 06 28 PM" src="https://user-images.githubusercontent.com/113581903/190344737-d842e3e9-bdd3-4c5b-80fa-e308715e8f66.png">

Select button not visible.
<img width="995" alt="Screenshot 2022-09-15 at 1 15 37 PM" src="https://user-images.githubusercontent.com/113581903/190346515-bc4558a5-4cbb-4649-9a3f-396a66aac3a2.png">

**Comment by mdaakhan** [comment]
Increasing the font size will disturb the visual appearance in long list
