### ISSUE TITLE
error in MD data analysis

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#65]
PIPL01
software-windows-hackathon exe

1.In run MD page I selected one combination and it's APO for MD, and left another out. However in data analysis, the left out combination is also seen in the target list.
![image](https://user-images.githubusercontent.com/111036161/190374117-ed5dfbc4-6c87-4e62-a529-dbac8074a0f5.png)
![image](https://user-images.githubusercontent.com/111036161/190374000-255d2b2c-0946-483d-9bf3-10c142df15f8.png)
![image](https://user-images.githubusercontent.com/111036161/190374499-4850d180-605d-48df-a4c4-2be71a92a581.png)

2. In average RMSD page, only the APO combination is showing for whole protein. For binding site, both APO and target-ligand combination is showing.
![image](https://user-images.githubusercontent.com/111036161/190374894-1ba91a77-f980-42b0-86a4-79c3b27e078b.png)
![image](https://user-images.githubusercontent.com/111036161/190375050-6e0f370f-b546-4453-9d2c-eee67045e49d.png)
 
3. In number of H bond plot, The combination that I did not perform MD on is also visible.
![image](https://user-images.githubusercontent.com/111036161/190375508-18648e9a-6d22-40e0-b301-bf6e5e6a6058.png)

**Comment by mdaakhan** [comment]
Fixed in not visible in new EXE
