### ISSUE TITLE
Inaccurate information in help texts of FES

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#66]
software-windows version- hackathon exe

1.In time of setting FES parameters the option for NPT simulation time shows a pop up saying it should be 0.1 or greater in ns. However FES will not run with 0.1ns and it needs to be 1 or greater in ns.
![image](https://user-images.githubusercontent.com/111036161/190379514-be888b55-6e65-47ce-8a40-60bd7d96ec59.png)

2. The lines in the help text is not comprehensive.
![image](https://user-images.githubusercontent.com/111036161/190379577-a8969054-041d-478a-b412-eba7b4b50158.png)

**Comment by mdaakhan** [comment]
Mis interpreted
