### ISSUE TITLE
BlindDocking - Showing same grid output for all ligand molecules 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#7]
Blinddock output - 

![XESS_Blinddock_OutputSameForLigand3](https://user-images.githubusercontent.com/105902516/184276741-88eabb70-62c0-4e34-9d14-843d9883aeec.jpg)
![XESS_Blinddock_OutputSameForLigand2](https://user-images.githubusercontent.com/105902516/184276753-f0370c2a-38a3-449a-befe-647e02f0cb7c.jpg)
![XESS_Blinddock_OutputSameForLigand1](https://user-images.githubusercontent.com/105902516/184276770-e673ab4d-b38d-49c4-9218-c7d2146527e1.jpg)

**Comment by chandkc** [comment]
When @SumedhaBhosale toggles, the ligand the table doesnot update.

**Comment by mdaakhan** [comment]
fixed
