### ISSUE TITLE
Disable NEXT button

### ISSUE THREAD

**Issue by gurdev7** [chandkc/X-ESS#77]
After setting grid parameter user tends to click on the next button. Confusing!
<img width="1168" alt="Screenshot 2022-09-28 at 12 28 19 PM" src="https://user-images.githubusercontent.com/113581903/192710007-0088331b-d687-4cfe-a710-5cdf2e8b9fc8.png">

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
