### ISSUE TITLE
Waiting time in error column

### ISSUE THREAD

**Issue by gurdev7** [chandkc/X-ESS#78]
<img width="1159" alt="Screenshot 2022-09-28 at 3 55 06 PM" src="https://user-images.githubusercontent.com/113581903/192756108-0119f201-af0a-45a0-87b9-9eeac87673b9.png">

**Comment by mdaakhan** [comment]
Error --> Message
34 s to Analysis

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
