### ISSUE TITLE
Blinddocking - Output error message wrongly popping-up

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#8]
After completing the blind docking job, upon clicking on 'Next', "Output files for blind docking - Select combination - not found" - error message pops-up. 

![XESS_Blinddock_OutputError](https://user-images.githubusercontent.com/105902516/184278034-3601af86-5baa-47e7-ac3c-e25df52c2d0d.jpg)

**Comment by chandkc** [comment]
Fixed
