### ISSUE TITLE
Blind Docking: Grid Parameters

### ISSUE THREAD

**Issue by chandkc** [chandkc/X-ESS#82]
We can suggest the user the grid parameters at the 'grid parameter section'

![Screen Shot 2022-09-28 at 3 42 05 PM](https://user-images.githubusercontent.com/105489779/192759318-7e26e621-c82d-4884-94af-099bfd5773c5.png)
![Screen Shot 2022-09-28 at 3 45 50 PM](https://user-images.githubusercontent.com/105489779/192759394-bac12c9c-9804-4e14-8828-a7f41e39aeab.png)

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
