### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by gurdev7** [chandkc/X-ESS#84]
I resubmitted the first job. The error message should reset too.

<img width="1161" alt="Screenshot 2022-09-28 at 4 18 45 PM" src="https://user-images.githubusercontent.com/113581903/192760646-bc035a11-f97e-4d72-a487-06dd2d52d8ed.png">

**Comment by gurdev7** [comment]
<img width="1159" alt="Screenshot 2022-09-28 at 3 55 06 PM" src="https://user-images.githubusercontent.com/113581903/192762627-05a595d8-bc0a-48e0-8ed6-8149611acb2b.png">

I resubmitted the third job...the first job also showing running.

**Comment by chandkc** [comment]
Implemented.
