### ISSUE TITLE
"OK" button not working in Advanced EM paramter section 

### ISSUE THREAD

**Issue by sujitpre** [chandkc/X-ESS#88]
After modifying cut-off criteria/energy convergence criteria from its default value in Advance EM parameter section, the "OK" and "Cancel" button become disable.
![Screenshot from 2022-09-28 17-55-06](https://user-images.githubusercontent.com/105837333/192940868-c19bfb27-6f0d-4802-902e-d66869002ceb.png)

**Comment by mdaakhan** [comment]
@LobeliaG please check

**Comment by mdaakhan** [comment]
COmmit id 002a69b Oct 11 2022
