### ISSUE TITLE
Blinddocking - To calculate 'Lowest Binding Energy' - use only probe molecule and not ALL input compounds

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/X-ESS#9]
Hi,

Currently, to calculate Lowest binding energy, all input molecules are been taken. It should only take Probe molecule selected by user.  

In the backend, once fill files are generated for each compound, only probe molecule should be taken ahead for autogrid and autodock.

**Comment by mdaakhan** [comment]
Fixed With Discussion with Sudip Sir on Sep 7 
Commit ID 986de25
