### ISSUE TITLE
Terminate job utility is not working properly

### ISSUE THREAD

**Issue by sujitpre** [chandkc/X-ESS#90]
After clicking terminate jobs multiple times for all protein systems the MD simulation job was running in background. 
![Screenshot from 2022-09-28 19-02-37](https://user-images.githubusercontent.com/105837333/192944901-938c912a-a5bc-487c-b528-e92c8c012483.png)
![Screenshot from 2022-09-28 19-03-41](https://user-images.githubusercontent.com/105837333/192944936-f416a825-4217-4868-b6ac-d2a79a7207c5.png)
![Screenshot from 2022-09-28 19-04-31](https://user-images.githubusercontent.com/105837333/192944996-04d1bb10-3e35-4c7d-9b77-5a23a182e7d3.png)

**Comment by chandkc** [comment]
@prescienceit The terminate script is different. We have gromacs specific termination scripts. The script being sent is of gmx 2018.

**Comment by sujitpre** [comment]
The image of terminate2.sh posted as requested.
![Screenshot from 2022-10-14 13-39-28](https://user-images.githubusercontent.com/105837333/195796400-da7cd1b1-dea1-45bd-93cb-434cadc78828.png)

**Comment by chandkc** [comment]
Resolved!
