### ISSUE TITLE
The simulation data ouput frequency (xtc, log) does not match with the mentioned output frequency in UI

### ISSUE THREAD

**Issue by sujitpre** [chandkc/X-ESS#92]
2 ps is output frequency mentioned in UI but nvt.xtc , npt.xtc, and log files are written after 4 ps.
![Screenshot from 2022-09-29 18-08-43](https://user-images.githubusercontent.com/105837333/193039119-86d86ee8-2642-4876-9572-bf92af87db79.png)
![Screenshot from 2022-09-29 18-09-58](https://user-images.githubusercontent.com/105837333/193039176-1a24b23e-1ea9-4e29-abcd-25377a426148.png)
![Screenshot from 2022-09-29 18-15-09](https://user-images.githubusercontent.com/105837333/193039264-ce93f075-7941-4d3c-b93e-8559f23d50e9.png)

**Comment by chandkc** [comment]
Since nvt and npt are the part of equilibration, we have a const. freq. output. We are only changing, from the UI, the output freq. of the npt_flex
