### ISSUE TITLE
Hydrogen bonding group lists one wrong atom name in acceptor atom type column

### ISSUE THREAD

**Issue by sujitpre** [chandkc/X-ESS#95]
Pymol image viewer shows that O4 atom of ligand (instead of O3 atom) should form Hbond with HG1 of Ser-280 as per distance criteria. PPAR_Imiglitazar is tested.  
![Screenshot from 2022-09-30 06-45-53](https://user-images.githubusercontent.com/105837333/193172888-c64af3ac-dca5-4e42-86c1-d1f66704ff3c.png)
![Screenshot from 2022-09-30 06-45-38](https://user-images.githubusercontent.com/105837333/193173030-c4a668d9-df09-4be8-acf8-fda9ecfc8f74.png)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
