### ISSUE TITLE
MD-MMPBSA- Data not shown when selected 'all proteins'

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/X-ESS#97]
PRinS_V_2_D_HA_2 - windows version
machine- PIPL01

The results for MMPBSA are not displayed when selected 'all proteins'. They are displayed when the proteins are selected one by one.
![image](https://user-images.githubusercontent.com/111036161/193285942-fe05db46-8a68-4880-996a-74e3636d8752.png)
![image](https://user-images.githubusercontent.com/111036161/193286061-91b4cc2e-57e7-4fb5-8788-2566c449018f.png)

**Comment by chandkc** [comment]
Resolved!
