### ISSUE TITLE
Sorting in MD jobs run UI

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/X-ESS#98]
Sorting by any of the columns in the MD run UI messes up the entire data in the end UI end.

![Screen Shot 2022-10-05 at 8 53 10 AM](https://user-images.githubusercontent.com/105898169/194078815-ee5963d7-5084-43b6-84b1-35ea534aa2a2.png)

**Comment by mdaakhan** [comment]
Resolved in Previous version clearing open issues
